apiVersion: v1
kind: Pod
metadata:
  
  name: worker
  labels:
    app: worker
spec:
  #
  # The specification is a list of attributes, one of which
  # is the list of containers
  # 
  restartPolicy: Never
  containers:
  - name: worker
    image: zhwa3087/demucs-test:v11
    imagePullPolicy: Always
    env:
    - name: REDIS_HOST
      value: "redis"
    - name: REDIS_PORT
      value: "6379"
    - name: MINIO_HOST
      value: "minio:9000"
    - name: MINIO_USER
      value: "rootuser"
    - name: MINIO_PASSWD
      value: "rootpass123"