apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: rest
spec:
  selector:
    matchLabels:
      app: rest
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: master
        image: zhwa3087/demucs-rest:v14
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio:9000"
        - name: MINIO_USER
          value: "rootuser"
        - name: MINIO_PASSWD
          value: "rootpass123"
        ports:
        - containerPort: 5005